// Vuejs/Day2/Frontend/src/components/navbar.vue
<template>
  <div class="navbar-light bg-light">
    <nav class="navbar navbar-expand-lg container">
      <a class="navbar-brand" href="#">Buyoo</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item active">
            <router-link class="nav-link" to="/products">Home</router-link>
          </li>
          <li class="nav-item">
            <router-link class="nav-link" to="/add">Add Products</router-link>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</template>

<script>
export default {
  name: "Navbar",
};
</script>

<style scoped></style>

// RWD/Day3/Frontend-Movies/src/Components/Navbar/Navbar.jsx
import { Link } from "react-router-dom";

const Navbar = () => {
  return (
    <nav className="navbar navbar-expand-lg bg-info">
      <div className="m-auto">
        <Link className="navbar-brand" to="/movies">
          Home
        </Link>
        <Link className="navbar-brand" to="/movies/add">
          Add
        </Link>
      </div>
    </nav>
  );
};

export default Navbar;
